export const BUTTON_NAMES = [
  'sample_desktop',
  'import_desktop',
  'insights_toggle',
  'mobile_menu_toggle',
  'sample_mobile_menu',
  'import_mobile_menu',
  'clear_mobile_menu',
  'conversion_plain',
  'conversion_readable',
  'conversion_ai',
  'references_toggle',
  'ocr_cancel',
  'ocr_run',
  'mobile_input_tab',
  'mobile_output_tab',
  'mobile_both_tab',
  'sample_mobile',
  'import_mobile',
  'clear_mobile',
  'clear_editor',
  'dismiss_error',
  'export_txt',
  'export_docx',
  'copy_output',
  'insights_close',
  'deep_scan_cancel',
  'deep_scan_repeat',
  'deep_scan_retry',
  'deep_scan_run',
  'select_all_findings',
  'redact_findings',
  'semantic_cancel',
  'semantic_retry',
  'semantic_run',
  'faq_toggle',
] as const;

export type ButtonName = (typeof BUTTON_NAMES)[number];
